INSERT INTO event (event_name,
                   description,
                   start_date,
                   end_date,
                   street,
                   postal_code,
                   city,
                   country,
                   availability,
                   price,
                   category,
                   organizer)
VALUES ("Men's Circle",
        "This is a Men's Circle",
        "2021-11-26 10:00",
        "2021-11-26 14:00",
        "Nowolipki 15",
        "04-781",
        "Warsaw",
        "Poland",
        15,
        "0.00",
        "MEN_CIRCLES",
        "Sebastian")
;