INSERT INTO event (event_name,
                   description,
                   start_date,
                   start_time,
                   end_date,
                   end_time,
                   street,
                   postal_code,
                   city,
                   country,
                   availability,
                   price,
                   category,
                   organizer)
VALUES ("Men's Circle",
        "This is a Men's Circle",
        "2021-11-26",
        "08:00",
        "2021-11-26",
        "15:30",
        "Nowolipki 15",
        "04-781",
        "Warsaw",
        "Poland",
        15,
        "0.00",
        "MEN_CIRCLES",
        "Sebastian"),
       ("Movement Medicine",
        "This is a Movement Medicine",
        "2021-11-29",
        "10:00",
        "2021-11-29",
        "17:30",
        "Nowogrodzka 10",
        "02-300",
        "Warsaw",
        "Poland",
        30,
        "10.00",
        "MOVEMENT",
        "Sebastian")
;